server.port=8443

spring.main.allow-bean-definition-overriding=true

server.ssl.key-store=classpath:/etc/cas/thekeystore
server.ssl.key-store-password=changeit

# Database Authentication
cas.authn.jdbc.query[0].sql=SELECT password FROM users WHERE username=?
cas.authn.jdbc.query[0].fieldPassword=password
cas.authn.jdbc.query[0].driverClass=com.mysql.cj.jdbc.Driver
cas.authn.jdbc.query[0].url=jdbc:mysql://localhost:3306/cas?useSSL=false&serverTimezone=UTC
cas.authn.jdbc.query[0].user=root
cas.authn.jdbc.query[0].password=root
cas.authn.jdbc.query[0].name=DbAuthenticationHandler

# Password handling
#cas.authn.jdbc.query[0].passwordEncoder.type=NONE
cas.authn.jdbc.query[0].passwordEncoder.type=BCRYPT

# Optional: Fetch additional attributes
cas.authn.jdbc.query[0].principalAttributeList=displayName:display_name,phoneNumber:phone

# Debugging logs
logging.level.org.apereo.cas=DEBUG
logging.level.org.apereo.cas.authentication=DEBUG
logging.level.org.apereo.cas.authn=DEBUG